#!/bin/sh

if [ ! -e /home/ami-setup/.git ]; then
echo "Must clone ami-setup to /home/ami-setup"
exit 1
fi

yum -y shell <<EOF
install cloud-init
install patch
install ed
install git
install gcc
install make
install perl
install xinetd
install ntp
install ltrace
install nc
install nmap
install wireshark
install cloud-utils-growpart
install rsync
install perl-JSON
install vim-enhanced
install perl-Digest-SHA
install perl-Digest-SHA1 
install perl-Digest-MD5
install perl-Cache-Memcached
install perl-Net-DNS
install perl-Net-SSH
install perl-Net-SSH-Perl
install perl-Net-SSH2 
install perl-MIME-Lite 
install readline-devel
install memcached
install httpd
install httpd-devel 
install mod_ssl 
install mod_gnutls
install msmtp
install perl-Net-Amazon-S3
install perl-Net-Amazon-EC2
install iotop
install xauth
install glibc-static
install zlib-static
install libcurl-devel
install tidy
install perltidy
install perl-LWP-Protocol-https
install perl-MongoDB
install make
install lsof
install psmisc
install sysstat
install dstat 
install lvm2
install yum-plugin-rpm-warm-cache
install bind-utils
install traceroute
install mtr
install zip
install unzip
install bzip2
install lzma
install tree
install time
install sqlite
install rpm-build
install perl-Term-ReadLine-Gnu
install perl-Term-ReadLine-Perl
install mailx
install iptraf-ng
install iperf
install fping
install ethtool
install dos2unix
install dnsmasq
install sendmail
install sendmail-cf
install telnet
install s3cmd
install httpd
install rsyslog-relp
install strace
install ltrace
install mbuffer
install yajl
install glibc-devel
install gcc-c++
install mod_php
install pcre-devel
install sqlite-devel
install openssl-devel
install tidy-devel
upgrade
run
EOF
